Repository thoth-station/workload-operator, pull requests merged in 2019-08, with the labels that each got.

#45 Automatic update of dependency thoth-common from 0.9.5 to 0.9.6
  Pipfile.lock
Labels: bot

#46 Start using Thoth in OpenShift's s2i
  .s2i/bin/assemble
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: size/M

#47 Stop using extras in thoth-common
  Pipfile
  Pipfile.lock
Labels: size/L

#48 Initial dependency lock
  Pipfile.lock
Labels: bot, size/L

#49 Automatic update of dependency thoth-common from 0.9.7 to 0.9.8
  Pipfile.lock
Labels: bot

#50 Added config
  .thoth.yaml
Labels: approved, size/S, size/XS
