Repository thoth-station/workload-operator, pull requests merged in 2019-09, with the labels that each got.

#51 Start using Thoth's base image
  .s2i/bin/assemble
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#52 Propagate deployment name for sentry environment
  openshift/deployment-template.yaml
Labels: approved, size/XS

#54 Automatic update of dependency thoth-common from 0.9.9 to 0.9.10
  Pipfile.lock
Labels: bot
