Repository thoth-station/workload-operator, pull requests merged in 2019-06, with the labels that each got.

#34 Automatic update of dependency thoth-common from 0.8.7 to 0.8.11
  Pipfile.lock
Labels: bot

#35 Automatic update of dependency pyyaml from 5.1 to 5.1.1
  Pipfile.lock
Labels: bot

#36 Add build trigger with generic webhook
  .zuul.yaml
  openshift/buildConfig-template.yaml
Labels: approved, size/S

#37 Handle conflicting workloads - just warn, do not report them
  app.py
Labels: approved, size/XS

#38 Automatic update of dependency thoth-common from 0.8.11 to 0.9.0
  Pipfile.lock
Labels: bot

#39 Automatic update of dependency thoth-common from 0.9.0 to 0.9.1
  Pipfile.lock
Labels: bot
