Repository thoth-station/workload-operator, pull requests merged in 2020-04, with the labels that each got.

#109 Automatic update of dependency thoth-common from 0.12.4 to 0.12.5
  Pipfile.lock
Labels: bot, size/S

#110 Automatic update of dependency pyyaml from 3.13 to 5.3.1
  Pipfile.lock
Labels: bot, size/M

#112 Automatic update of dependency thoth-common from 0.12.5 to 0.12.6
  Pipfile.lock
Labels: bot, size/XS

#113 Remove latest version restriction from .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#114 Automatic update of dependency thoth-common from 0.12.6 to 0.12.7
  Pipfile.lock
Labels: bot, size/S

#115 Automatic update of dependency thoth-common from 0.12.7 to 0.12.9
  Pipfile.lock
Labels: bot, size/S

#116 Automatic update of dependency thoth-common from 0.12.9 to 0.12.10
  Pipfile.lock
Labels: bot, size/S

#117 Automatic update of dependency thoth-common from 0.12.10 to 0.13.0
  Pipfile.lock
Labels: bot, size/XS

#118 Automatic update of dependency thoth-common from 0.13.0 to 0.13.1
  Pipfile.lock
Labels: bot, size/XS

#119 Automatic update of dependency click from 7.1.1 to 7.1.2
  Pipfile.lock
Labels: bot, size/XS

#120 Automatic update of dependency thoth-common from 0.13.1 to 0.13.2
  Pipfile.lock
Labels: bot, size/S
