Repository thoth-station/workload-operator, pull requests merged in 2020-02, with the labels that each got.

#87 Automatic update of dependency thoth-common from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: bot, size/XS

#88 Automatic update of dependency thoth-common from 0.10.2 to 0.10.3
  Pipfile.lock
Labels: bot, size/S

#89 Automatic update of dependency thoth-common from 0.10.3 to 0.10.4
  Pipfile.lock
Labels: bot, size/XS

#90 Automatic update of dependency thoth-common from 0.10.4 to 0.10.5
  Pipfile.lock
Labels: bot, size/S

#80 Disable dry run for Thoth's recommendations
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#91 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#93 Fallback to Pipfile.lock present in the repo on any Thoth error
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#94 Automatic update of dependency thoth-common from 0.10.5 to 0.10.6
  Pipfile.lock
Labels: bot, size/S

#95 Automatic update of dependency thoth-common from 0.10.6 to 0.10.7
  Pipfile.lock
Labels: bot, size/S

#96 Automatic update of dependency thoth-common from 0.10.7 to 0.10.8
  Pipfile.lock
Labels: bot, size/S

#97 Automatic update of dependency thoth-common from 0.10.8 to 0.10.9
  Pipfile.lock
Labels: bot, size/S
